name: MenuBox
main: cn.jji8.MenuBox.main
version: 1.0
author: jianjianai
api-version: 1.13
commands:
  openbox:
    aliases: [打开菜单,dkcd,dakaicaidan]
    description: "打开菜单命令"
    permission: MenuBox.openbox
    permission-message: "你没有权限执行此命令"
    usage: /<command> 菜单名字 玩家名字
  generatebox:
    aliases: [生成菜单,shengchengcaidan,sccd]
    description: "生成菜单命令"
    permission: MenuBox.generatebox
    permission-message: "你没有权限执行此命令"
    usage: /<command>
  preservationbox:
    aliases: [保存菜单,baocuncaidan,bccd]
    description: "保存菜单命令"
    permission: MenuBox.preservationbox
    permission-message: "你没有权限执行此命令"
    usage: /<command> 菜单名字
  editbox:
    aliases: [编辑菜单,bianjicaidan,bjcd]
    description: "保存菜单命令"
    permission: MenuBox.editbox
    permission-message: "你没有权限执行此命令"
    usage: /<command>